### ISSUE TITLE
Unstable after upgrade to TNS 3.X

### ISSUE THREAD

**Issue by manijak** [PeterStaev/NativeScript-Grid-View#19]
After upgrading the plugin to latest version, I can run the app just fine in emulators, but as soon as I start the app on a real device, it crashes with the following log.
The device is a Nvidia Shield tablet, running Android 7.0

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.0.3           │ 3.0.3          │ Up to date  │
│ tns-core-modules │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-android      │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-ios          │ 3.0.1           │ 3.0.1          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onLayout failed

Error: java.lang.IllegalArgumentException: Span count should be at least 1. Provided 0
    android.support.v7.widget.GridLayoutManager.setSpanCount(GridLayoutManager.java:814)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
    com.tns.Runtime.callJSMethod(Runtime.java:890)
    com.tns.Runtime.callJSMethod(Runtime.java:874)
    com.tns.Runtime.callJSMethod(Runtime.java:866)
    com.tns.gen.android.support.v7.widget.RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerView.onLayout(RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerView.java:26)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
    org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
    org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
    org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
    org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
    org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
    org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
    android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
    android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
    android.view.View.layout(View.java:17519)
    android.view.ViewGroup.layout(ViewGroup.java:5612)
    android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2489)
    android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2191)
    android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1343)
    android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6526)
    android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
    android.view.Choreographer.doCallbacks(Choreographer.java:683)
    android.view.Choreographer.doFrame(Choreographer.java:619)
    android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
    android.os.Handler.handleCallback(Handler.java:751)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6120)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
File: "file:///data/data/ba.fkz.myapp/files/app/tns_modules/nativescript-grid-view/grid-view.js, line: 118, column: 22

StackTrace: 
	Frame: function:'GridView.refresh', file:'file:///data/data/ba.fkz.myapp/files/app/tns_modules/nativescript-grid-view/grid-view.js', line: 118, column: 23
	Frame: function:'GridView.onLayout', file:'file:///data/data/ba.fkz.myapp/files/app/tns_modules/nativescript-grid-view/grid-view.js', line: 110, column: 14
	Frame: function:'GridViewRecyclerView.onLayout', file:'file:///data/data/ba.fkz.myapp/files/app/tns_modules/nativescript-grid-view/grid-view.js', line: 243, column: 19


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
	at com.tns.Runtime.callJSMethod(Runtime.java:890)
	at com.tns.Runtime.callJSMethod(Runtime.java:874)
	at com.tns.Runtime.callJSMethod(Runtime.java:866)
	at com.tns.gen.android.support.v7.widget.RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerView.onLayout(RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerView.java:26)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
	at android.view.View.layout(View.java:17519)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2489)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2191)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1343)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
	at android.view.Choreographer.doFrame(Choreographer.java:619)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6120)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.IllegalArgumentException: Span count should be at least 1. Provided 0
	at android.support.v7.widget.GridLayoutManager.setSpanCount(GridLayoutManager.java:814)
	... 65 more
```

**Comment by PeterStaev** [comment]
@manijak , seems something related to the size of the items and device. Can you tell me what is the value you have for `colWidth` and what is the device width?

**Comment by manijak** [comment]
@PeterStaev , sorry for the late reply. 
Ok so I have managed to reproduce this on emulator as well. I use the GridView in my tablet views e.g. `.minW600.xml`. I created a CustomTablet in Genymotion to mimic the exact resolution and dip: 1920x1200 dip 320. 

When starting up in portrait mode, the device width is: `600`. 
`colWidth` is 300. `rowHeight` is 220. Doesn't matter what I put here, still crashes. 

```xml
<gv:GridView items="{{ videolist }}" colWidth="300" rowHeight="220" verticalSpacing="0" horizontalSpacing="0">
...
</gv:GridView>
```

**Comment by manijak** [comment]
I've changed the title of the issue. It seems to happen on phones and tables, on emulator and device. It is also unstable on both platforms. 

iOS: Sometimes it doesn't render the GridView at all, show just blank page. (Could be a livesync issue). 

Android: Crashes on startup. Seems like `_effectiveColWidth` is always 0. Even tho it is set in XML.

**Comment by PeterStaev** [comment]
@manijak , the android problems should be resolved with the new version on npm. For iOS sadly I could not simulate any instabilities.

**Comment by manijak** [comment]
Thanks, confirmed working now. 

Forget the iOS issue, not related to this plugin. I am calculating colWidth based on device rotation. TNS gives the wrong values here.
