### ISSUE TITLE
Calling js method onLayout failed (crash app on android)

### ISSUE THREAD

**Issue by christo-pr** [PeterStaev/NativeScript-Grid-View#39]
Hi! i've using this plugin with nativescript for an ios app, so now that im trying to build the app for android, everything works fine until i visit a page with a list using this plugin.

Component | Current version |
------------ | ----------------|
nativescript | 3.4.2 | 
tns-core-modules | 3.1.1|
tns-android  | 3.4.2 |
nativescript-grid-view| 3.4.0|

like i said, everything works in ios, but with android i get this error always i go to a page where this plugin is been use:

```
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onLayout failed
System.err: Error: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
System.err:     android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
System.err:     android.support.v7.widget.DefaultItemAnimator.animateMove(DefaultItemAnimator.java:255)
System.err:     android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:317)
System.err:     android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
System.err:     android.support.v7.widget.RecyclerView$4.processPersistent(RecyclerView.java:532)
System.err:     android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:241)
System.err:     android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3653)
System.err:     android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
System.err:     android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.android.support.v7.widget.RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerViewImpl.onLayout(RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerViewImpl.java:26)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.DockLayout.onLayout(DockLayout.java:173)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
System.err:     android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
System.err:     android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
System.err:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
System.err:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
System.err:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
System.err:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
System.err:     android.view.Choreographer.doCallbacks(Choreographer.java:580)
System.err:     android.view.Choreographer.doFrame(Choreographer.java:550)
System.err:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
System.err:     android.os.Handler.handleCallback(Handler.java:739)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5254)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/org.nativescript.app-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.app-1/lib/x86, /vendor/lib, /system/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:511)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:469)
System.err:     android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
System.err:     android.support.v7.widget.DefaultItemAnimator.animateMove(DefaultItemAnimator.java:255)
System.err:     android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:317)
System.err:     android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
System.err:     android.support.v7.widget.RecyclerView$4.processPersistent(RecyclerView.java:532)
System.err:     android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:241)
System.err:     android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3653)
System.err:     android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
System.err:     android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.android.support.v7.widget.RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerViewImpl.onLayout(RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerViewImpl.java:26)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.DockLayout.onLayout(DockLayout.java:173)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
System.err:     android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
System.err:     android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err:     android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err:     android.view.View.layout(View.java:15671)
System.err:     android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err:     android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
System.err:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
System.err:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
System.err:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
System.err:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
System.err:     android.view.Choreographer.doCallbacks(Choreographer.java:580)
System.err:     android.view.Choreographer.doFrame(Choreographer.java:550)
System.err:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
System.err:     android.os.Handler.handleCallback(Handler.java:739)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5254)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: File: "file:///data/data/org.nativescript.app/files/app/tns_modules/nativescript-grid-view/grid-view.js, line: 340, column: 38
System.err: StackTrace: 
System.err: 	Frame: function:'GridViewRecyclerViewImpl.onLayout', file:'file:///data/data/org.nativescript.app/files/app/tns_modules/nativescript-grid-view/grid-view.js', line: 340, column: 39
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.android.support.v7.widget.RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerViewImpl.onLayout(RecyclerView_frnal_ts_helpers_l58_c38__GridViewRecyclerViewImpl.java:26)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.DockLayout.onLayout(DockLayout.java:173)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
System.err: 	at android.view.View.layout(View.java:15671)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:550)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
System.err: 	at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
System.err: 	at android.support.v7.widget.DefaultItemAnimator.animateMove(DefaultItemAnimator.java:255)
System.err: 	at android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:317)
System.err: 	at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
System.err: 	at android.support.v7.widget.RecyclerView$4.processPersistent(RecyclerView.java:532)
System.err: 	at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:241)
System.err: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3653)
System.err: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
System.err: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
System.err: 	... 64 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/org.nativescript.app-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.app-1/lib/x86, /vendor/lib, /system/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
System.err: 	... 73 more
System.err: 	Suppressed: java.lang.ClassNotFoundException: android.support.v4.animation.AnimatorCompatHelper
System.err: 		at java.lang.Class.classForName(Native Method)
System.err: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
System.err: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
System.err: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
System.err: 		... 74 more
System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
any solution to this???

**Comment by PeterStaev** [comment]
Hey @CrystalStream , seems there is some problem with your support libs/version. You can try this and see if this it would help: https://stackoverflow.com/questions/42987363/java-lang-noclassdeffounderror-failed-resolution-of-landroid-support-v4-animat/43043372 

Or you can try fixing the version of the support lib being used by adding the following to your `app.gradle` file:
```groovy
project.ext {
    supportVersion = "23.1.0"
}
```
