### ISSUE TITLE
Cannot read property 'widget' of undefined

### ISSUE THREAD

**Issue by rakeshgirase** [PeterStaev/NativeScript-Grid-View#59]
After Nativescript 6.0 upgrade I started getting following exception on Android devices:
```
Calling js method onCreateView failed
TypeError: Cannot read property 'widget' of undefined

StackTrace:
Frame: function:'initGridViewRecyclerView', file:'file:///data/data/org.nativescript.preview/files/app/nativescript-grid-view/grid-view.js', line: 364, column: 26
Frame: function:'GridView.createNativeView', file:'file:///data/data/org.nativescript.preview/files/app/nativescript-grid-view/grid-view.js', line: 34, column: 9
Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 491, column: 25
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 13
Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 20
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 992, column: 10
Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 10
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 13
Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 20
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 992, column: 10
Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 10
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 13
Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 7
Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 126, column: 36
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 992, column: 10
Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 10
Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 12
Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 10
Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 684, column: 13
Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 26, column: 34
at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
at com.tns.Runtime.callJSMethod(Runtime.java:1109)
at com.tns.Runtime.callJSMethod(Runtime.java:1089)
at com.tns.Runtime.callJSMethod(Runtime.java:1081)
at com.tns.FragmentClass.onCreateView(FragmentClass.java:54)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:7325)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
A sample project is created https://play.nativescript.org/?template=play-tsc&id=TcHeUQ&v=292. IOS works fine. This  might be because the AndroidX is enabled by default in NS 6.0

**Comment by rakeshgirase** [comment]
I changed following classes to androidX format and it started working. 
```
android.support.v7.widget.GridLayoutManager to androidx.recyclerview.widget.GridLayoutManager

android.support.v7.widget.LinearLayoutManager.HORIZONTAL to androidx.recyclerview.widget.LinearLayoutManager.HORIZONTAL

android.support.v7.widget.RecyclerView.OnScrollListener to androidx.recyclerview.widget.RecyclerView.OnScrollListener
```

The working example is at https://play.nativescript.org/?template=play-tsc&id=TcHeUQ&v=293.

**Comment by PeterStaev** [comment]
Hey @rakeshgirase, the fix for this is available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
